### ISSUE TITLE
About the costate value

### ISSUE THREAD

**Issue by 827915432** [luwin1127/direct-method-for-optimal-control#1]
Hi, I'm curous why the terminal value of costate is 0.1 not 0?
https://github.com/luwin1127/direct-method-for-optimal-control/blob/c53a3b46fd17f179ee690297ad2c3a48cd99b429/gradient-method-for-OCP/Steepest_descent_for_optimal_control.m#L17

**Comment by luwin1127** [comment]
sry for so long to reply to you.
You can set the terminal value of costate as 0, or any other number. Just because the performance of 0.1 is better.
